spring.application.name=training
spring.datasource.url=jdbc:postgresql://localhost:5432/training_db
spring.datasource.username=postgres
spring.datasource.password=haneen@123
spring.jpa.hibernate.ddl-auto=validate

slack.webhook.url=${SLACK_WEBHOOK_URL}